// Service worker: precaches the whole app so it works offline after the first visit.
// The VERSION/ASSETS block is generated by `npm run sw` (tools/update-sw.mjs).

// <generated>
const VERSION = 'eed3e7289700';
const ASSETS = [
  "./",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/audio/engine.js",
  "./src/config.js",
  "./src/core/camera.js",
  "./src/core/finalpass.js",
  "./src/core/quality.js",
  "./src/core/renderer.js",
  "./src/core/uniforms.js",
  "./src/debug.js",
  "./src/fish/dna.js",
  "./src/fish/fish.js",
  "./src/fish/geometry.js",
  "./src/fish/material.js",
  "./src/fish/paint.js",
  "./src/fish/school.js",
  "./src/glsl/common.js",
  "./src/input.js",
  "./src/main.js",
  "./src/particles/bubbles.js",
  "./src/particles/plankton.js",
  "./src/particles/shadows.js",
  "./src/styles.css",
  "./src/sw-client.js",
  "./src/ui/start.js",
  "./src/util/math.js",
  "./src/util/noise.js",
  "./src/util/rng.js",
  "./src/world/background.js",
  "./src/world/caustics.js",
  "./src/world/chest.js",
  "./src/world/corals.js",
  "./src/world/crab.js",
  "./src/world/godrays.js",
  "./src/world/jellyfish.js",
  "./src/world/rocks.js",
  "./src/world/sand.js",
  "./src/world/seaweed.js",
  "./src/world/surface.js",
  "./src/world/world.js",
  "./vendor/three/LICENSE",
  "./vendor/three/build/three.core.js",
  "./vendor/three/build/three.module.js",
  "./vendor/three/examples/jsm/geometries/RoundedBoxGeometry.js",
  "./vendor/three/examples/jsm/postprocessing/EffectComposer.js",
  "./vendor/three/examples/jsm/postprocessing/MaskPass.js",
  "./vendor/three/examples/jsm/postprocessing/Pass.js",
  "./vendor/three/examples/jsm/postprocessing/RenderPass.js",
  "./vendor/three/examples/jsm/postprocessing/ShaderPass.js",
  "./vendor/three/examples/jsm/postprocessing/UnrealBloomPass.js",
  "./vendor/three/examples/jsm/shaders/CopyShader.js",
  "./vendor/three/examples/jsm/shaders/LuminosityHighPassShader.js",
  "./vendor/three/examples/jsm/utils/BufferGeometryUtils.js"
];
// </generated>

const CACHE = `akvariet-${VERSION}`;
const LOCAL = ['localhost', '127.0.0.1', '[::1]'].includes(self.location.hostname);

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('akvariet-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

async function fromNetwork(request) {
  const response = await fetch(request);
  if (response && response.ok && response.type === 'basic') {
    const cache = await caches.open(CACHE);
    cache.put(request, response.clone());
  }
  return response;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (LOCAL) {
    // Development: always fresh, cache only as an offline fallback.
    event.respondWith(fromNetwork(request).catch(() => caches.match(request, { ignoreSearch: true })));
    return;
  }
  // Production: instant start from cache; the network fills any gaps.
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => hit || fromNetwork(request)),
  );
});
